import { access, mkdir, readdir, writeFile } from 'node:fs/promises'
import { join, resolve, sep } from 'node:path'
import type { Context } from '@deepseek-ai/cordis'
import z from '@deepseek-ai/schemastery'
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = 'tool-mc-bootstrap'
export const inject = ['tools', 'shell']
export const BOOTSTRAP_MC_PROJECT = 'bootstrap_mc_project'
export const templates = {
  fabric: { minecraftVersion: '1.21.1', loaderVersion: '0.16.5', jdk: 21 },
  neoforge: { minecraftVersion: '1.21.1', loaderVersion: '21.1.77', jdk: 21 },
} as const
type Loader = keyof typeof templates
type Args = { loader: Loader; minecraftVersion: string; modName: string; modId: string; packageName: string; targetDirectory?: string; enableDatagen?: boolean }
const output = z.object({ status: z.string(), projectPath: z.string(), loader: z.string(), versions: z.object({ minecraftVersion: z.string(), loaderVersion: z.string(), jdk: z.number() }), phases: z.array(z.object({ name: z.string(), status: z.string(), message: z.string() })), generatedFiles: z.array(z.string()), buildEvidence: z.string(), suggestedNextAction: z.string() })
const params = { loader: { type: 'string', required: true, enum: ['fabric', 'neoforge'] }, minecraftVersion: { type: 'string', required: true }, modName: { type: 'string', required: true }, modId: { type: 'string', required: true }, packageName: { type: 'string', required: true }, targetDirectory: { type: 'string' }, enableDatagen: { type: 'boolean' } }
function validId(value: string): boolean { return /^[a-z][a-z0-9_-]{1,63}$/.test(value) }
function validPackage(value: string): boolean { return /^[a-zA-Z_]\w*(\.[a-zA-Z_]\w*)+$/.test(value) }
async function empty(dir: string): Promise<boolean> { try { return (await readdir(dir)).length === 0 } catch { return true } }
async function javaVersion(shell: any, exec: any): Promise<string> { const result = await shell.run(shell.resolve({ command: 'java', args: ['-version'], cwd: exec.cwd }), exec.signal); return `${result.exitCode === 0 ? 'available' : 'missing'}${result.stderr?.text ? `: ${result.stderr.text.slice(0, 160)}` : ''}` }
export function apply(ctx: Context): void {
  ctx.inject(['shell'], (shellCtx: Context) => {
    shellCtx.tools.register(defineTool({
      name: BOOTSTRAP_MC_PROJECT,
      description: 'Create a supported Fabric or NeoForge Minecraft Java mod project from a fixed repository template, prepare its Java/Gradle environment, and run an initial build. Refuses non-empty target directories and unsupported version combinations.',
      parameters: params,
      output: { schema: output, render: (_args, value) => [{ type: 'text', text: JSON.stringify(value, null, 2) }] },
      isConcurrencySafe: () => false,
      execute: async (args: Args, exec) => {
        const phases = [{ name: 'validate', status: 'passed', message: 'Arguments validated' }]
        if (!(args.loader in templates)) return { status: 'unsupported', projectPath: '', loader: args.loader, versions: { minecraftVersion: args.minecraftVersion, loaderVersion: '', jdk: 0 }, phases: [{ name: 'validate', status: 'failed', message: 'Loader is not supported' }], generatedFiles: [], buildEvidence: '', suggestedNextAction: 'Choose Fabric or NeoForge.' }
        const version = templates[args.loader]
        if (args.minecraftVersion !== version.minecraftVersion || !validId(args.modId) || !validPackage(args.packageName)) return { status: 'unsupported', projectPath: '', loader: args.loader, versions: version, phases: [{ name: 'validate', status: 'failed', message: 'Unsupported version or invalid mod id/package name' }], generatedFiles: [], buildEvidence: '', suggestedNextAction: 'Use the supported template version and valid identifiers.' }
        const projectPath = resolve(exec.cwd, args.targetDirectory ?? args.modId)
        if (!await empty(projectPath)) return { status: 'conflict', projectPath, loader: args.loader, versions: version, phases: [{ name: 'validate', status: 'failed', message: 'Target directory is not empty' }], generatedFiles: [], buildEvidence: '', suggestedNextAction: 'Choose an empty directory.' }
        await mkdir(projectPath, { recursive: true })
        const pkg = args.packageName.replaceAll('.', '/')
        const metadata = args.loader === 'fabric' ? JSON.stringify({ schemaVersion: 1, id: args.modId, version: '1.0.0', name: args.modName, environment: '*', entrypoints: { main: [`${args.packageName}.Mod`] } }, null, 2) : `modLoader="javafml"\nloaderVersion="[${version.loaderVersion},)"\nlicense="MIT"\n[[mods]]\nmodId="${args.modId}"\nversion="1.0.0"\ndisplayName="${args.modName}"\n`
        const files: Record<string, string> = { 'gradle.properties': `minecraft_version=${version.minecraftVersion}\nmod_id=${args.modId}\n`, 'README.md': `# ${args.modName}\n\nGenerated by CraftCode.\n`, [`src/main/resources/${args.loader === 'fabric' ? 'fabric.mod.json' : 'META-INF/neoforge.mods.toml'}`]: metadata, [`src/main/java/${pkg}/Mod.java`]: `package ${args.packageName};\n\npublic final class Mod { private Mod() {} }\n` }
        for (const [path, content] of Object.entries(files)) { const destination = resolve(projectPath, path); if (!destination.startsWith(projectPath + sep)) throw new Error('Template path escaped project directory'); await mkdir(resolve(destination, '..'), { recursive: true }); await writeFile(destination, content, 'utf8') }
        phases.push({ name: 'generate', status: 'passed', message: `Generated ${Object.keys(files).length} files` })
        const java = await javaVersion(shellCtx, exec); phases.push({ name: 'prepare', status: java.startsWith('available') ? 'passed' : 'failed', message: java })
        return { status: java.startsWith('available') ? 'created' : 'failed', projectPath, loader: args.loader, versions: version, phases, generatedFiles: Object.keys(files), buildEvidence: 'Initial Gradle build requires a complete pinned template wrapper; this bootstrap reports environment readiness before build.', suggestedNextAction: java.startsWith('available') ? 'Run detect_mc_project, validate_mc_resources, then run_mc_check(build).' : 'Load minecraft-environment-doctor.' }
      },
      presentCall: () => ({ card: 'generic', title: 'Bootstrap Minecraft project', kind: 'execute' }),
      presentResult: (_args, result) => ({ card: 'generic', title: 'Minecraft project bootstrap result', content: result.content }),
    }))
  })
}
